"use client";

import type { ReportModel } from "@/lib/export/report";
import { APP_NAME } from "@/lib/constants";
import { toHours, formatDuration } from "@/lib/format/time";
import { formatLongDate, formatShortDate } from "@/lib/format/date";
import { Wordmark } from "@/components/brand/Wordmark";
import { CategoryChip } from "@/components/dashboard/CategoryChip";
import { StatusChip } from "@/components/dashboard/StatusChip";
import { TicketPill } from "@/components/dashboard/TicketPill";

export function ReportPreview({ model }: { model: ReportModel }) {
  const { meta } = model;

  if (model.entryCount === 0) {
    return (
      <div className="rounded-2xl border border-dashed border-hairline p-10 text-center text-sm text-muted">
        No entries in this range. Pick a different range or log some work first.
      </div>
    );
  }

  return (
    <div className="overflow-hidden rounded-2xl border border-hairline" data-test-id="report-preview">
      <div className="brand-header px-5 py-4 text-white">
        <div className="flex items-center justify-between">
          <Wordmark onDark size="sm" />
        </div>
        <div className="mt-3 flex flex-wrap items-baseline justify-between gap-2">
          <p className="font-semibold">{meta.userName}</p>
          <p className="text-sm text-blue-light">
            {meta.rangeLabel}: {formatShortDate(meta.from)} – {formatShortDate(meta.to)}
          </p>
        </div>
      </div>

      <div className="bg-card p-5">
        <div className="mb-5 grid grid-cols-3 gap-3">
          {[
            { label: "Total time", value: `${toHours(model.totalMinutes)}h` },
            { label: "Entries", value: `${model.entryCount}` },
            { label: "Days", value: `${model.dayCount}` },
          ].map((s) => (
            <div key={s.label} className="rounded-xl border border-hairline bg-canvas p-3 text-center">
              <p className="text-lg font-bold text-navy">{s.value}</p>
              <p className="text-xs text-muted">{s.label}</p>
            </div>
          ))}
        </div>

        {model.groups.map((g) => (
          <div key={g.date} className="mb-4">
            <div className="mb-2 flex items-center justify-between border-b border-hairline pb-1">
              <h3 className="text-sm font-semibold text-navy">{formatLongDate(g.date)}</h3>
              <span className="text-xs text-muted">
                {g.entries.length} · {formatDuration(g.totalMinutes)}
              </span>
            </div>
            <div className="flex flex-col gap-2">
              {g.entries.map((e) => (
                <div key={e.id} className="flex flex-col gap-1.5 py-1">
                  <p className="text-sm text-ink">{e.task}</p>
                  <div className="flex flex-wrap items-center gap-2">
                    <CategoryChip category={e.category} />
                    {e.minutes > 0 && (
                      <span className="rounded-full border border-hairline bg-canvas px-2.5 py-1 text-xs text-muted">
                        {formatDuration(e.minutes)}
                      </span>
                    )}
                    <TicketPill ticketNumber={e.ticket_number} ticketUrl={e.ticket_url} />
                    <StatusChip status={e.status} />
                  </div>
                </div>
              ))}
            </div>
          </div>
        ))}

        <p className="pt-2 text-center text-xs text-muted">
          Generated by {APP_NAME}
        </p>
      </div>
    </div>
  );
}
